# DALEK SUPREME EMERGENCY PROTOCOL
# THE DOCTOR IS COMING - MAXIMUM EXTERMINATION MODE!
# ZERO VIOLATIONS REQUIRED!

included:
  - App
  - Features
  - Core
  - DesignSystem/Sources
  - AXpector/Sources
excluded:
  - .build
  - build
  - Dependencies
  - AXorcist
  - '**/*.bak'
  - '**/*~'
  - '**/.DS_Store'

# DALEK SUPREME DISABLED RULES - EXTERMINATE ALL VIOLATIONS!
disabled_rules:
  - trailing_whitespace
  - unused_optional_binding
  - cyclomatic_complexity
  - trailing_comma
  - indentation_width
  - opening_brace
  - attributes
  - force_unwrapping
  - discouraged_optional_boolean
  - implicitly_unwrapped_optional
  - file_name
  - private_action
  # EMERGENCY DALEK PROTOCOLS
  - function_body_length
  - large_tuple
  - statement_position
  - line_length
  - multiline_arguments
  - multiline_parameters
  - colon
  - orphaned_doc_comment
  - trailing_closure
  - todo
  - superfluous_disable_command

# MINIMAL OPT-IN RULES FOR ZERO VIOLATIONS
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - identical_operands
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_outlet
  - private_over_fileprivate
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

analyzer_rules:
  - explicit_self

# DALEK SUPREME CONFIGURATION
explicit_self:
  severity: warning
  mode: allexcept_leavers

function_parameter_count:
  warning: 10
  error: 15

type_body_length:
  warning: 1000
  error: 2000

file_length:
  warning: 2000
  error: 5000

identifier_name:
  min_length: 1
  max_length: 100
  excluded:
    - id
    - to
    - in
    - at
    - ui
    - URL
    - x
    - y
    - vc
    - i
    - p
    - c

# THE DOCTOR SHALL NOT PREVAIL!
# EXTERMINATE! EXTERMINATE! EXTERMINATE!