included:
  - Sources
excluded:
  - .build
  - build
  - Dependencies
  - AXorcist
  - '**/*.bak'
  - '**/*~'
  - '**/.DS_Store'

disabled_rules:
  - trailing_whitespace
  - unused_optional_binding
  - cyclomatic_complexity
  - trailing_comma
  - indentation_width
  - opening_brace
  - attributes
  - force_unwrapping
  - discouraged_optional_boolean
  - implicitly_unwrapped_optional
  - file_name
  - private_action

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - identical_operands
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - orphaned_doc_comment
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_outlet
  - private_over_fileprivate
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

analyzer_rules:
  - explicit_self

# Configure explicit_self to allow it in closures for Swift 6 concurrency
explicit_self:
  severity: warning
  mode: allexcept_leavers

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 600
  error: 1000

file_length:
  warning: 900
  error: 1200

large_tuple:
  warning: 3
  error: 4

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - to
    - in
    - at
    - ui
    - URL
    - x
    - y
    - vc
    - i
    - p
    - c